export const CENTRAL_IMPORT_LIST_REQUEST = "CENTRAL_IMPORT_LIST_REQUEST";
export const CENTRAL_IMPORT_LIST_SUCCESS = "CENTRAL_IMPORT_LIST_SUCCESS";
export const CENTRAL_IMPORT_LIST_FAIL = "CENTRAL_IMPORT_LIST_FAIL";
export const CENTRAL_IMPORT_LIST_RESET = "CENTRAL_IMPORT_LIST_RESET";
