export const CENTRAL_RECEIPT_LIST_REQUEST = "CENTRAL_RECEIPT_LIST_REQUEST";
export const CENTRAL_RECEIPT_LIST_SUCCESS = "CENTRAL_RECEIPT_LIST_SUCCESS";
export const CENTRAL_RECEIPT_LIST_FAIL = "CENTRAL_RECEIPT_LIST_FAIL";
export const CENTRAL_RECEIPT_LIST_RESET = "CENTRAL_RECEIPT_LIST_RESET";

export const CENTRAL_RECEIPT_CREATE_REQUEST = "CENTRAL_RECEIPT_CREATE_REQUEST";
export const CENTRAL_RECEIPT_CREATE_SUCCESS = "CENTRAL_RECEIPT_CREATE_SUCCESS";
export const CENTRAL_RECEIPT_CREATE_FAIL = "CENTRAL_RECEIPT_CREATE_FAIL";
