export const LAGER_LIST_REQUEST = "LAGER_LIST_REQUEST";
export const LAGER_LIST_SUCCESS = "LAGER_LIST_SUCCESS";
export const LAGER_LIST_FAIL = "LAGER_LIST_FAIL";
export const LAGER_LIST_RESET = "LAGER_LIST_RESET";

export const LAGER_MATERIAL_LIST_REQUEST = "LAGER_MATERIAL_LIST_REQUEST";
export const LAGER_MATERIAL_LIST_SUCCESS = "LAGER_MATERIAL_LIST_SUCCESS";
export const LAGER_MATERIAL_LIST_FAIL = "LAGER_MATERIAL_LIST_FAIL";
