export const LAGER_LIST_REQUEST = "LAGER_LIST_REQUEST";
export const LAGER_LIST_SUCCESS = "LAGER_LIST_SUCCESS";
export const LAGER_LIST_FAIL = "LAGER_LIST_FAIL";
export const LAGER_LIST_RESET = "LAGER_LIST_RESET";

export const LAGER_MATERIAL_LIST_REQUEST = "LAGER_MATERIAL_LIST_REQUEST";
export const LAGER_MATERIAL_LIST_SUCCESS = "LAGER_MATERIAL_LIST_SUCCESS";
export const LAGER_MATERIAL_LIST_FAIL = "LAGER_MATERIAL_LIST_FAIL";

export const LAGER_ARTICLE_QUANTITY_REQUEST = "LAGER_ARTICLE_QUANTITY_REQUEST";
export const LAGER_ARTICLE_QUANTITY_SUCCESS = "LAGER_ARTICLE_QUANTITY_SUCCESS";
export const LAGER_ARTICLE_QUANTITY_FAIL = "LAGER_ARTICLE_QUANTITY_FAIL";

export const LAGER_ARTICLE_QUANTITIES_REQUEST =
  "LAGER_ARTICLE_QUANTITIES_REQUEST";
export const LAGER_ARTICLE_QUANTITIES_SUCCESS =
  "LAGER_ARTICLE_QUANTITIES_SUCCESS";
export const LAGER_ARTICLE_QUANTITIES_FAIL = "LAGER_ARTICLE_QUANTITIES_FAIL";

export const LAGER_ARTICLE_PURCHASE_PRICES_REQUEST =
  "LAGER_ARTICLE_PURCHASE_PRICES_REQUEST";
export const LAGER_ARTICLE_PURCHASE_PRICES_SUCCESS =
  "LAGER_ARTICLE_PURCHASE_PRICES_SUCCESS";
export const LAGER_ARTICLE_PURCHASE_PRICES_FAIL =
  "LAGER_ARTICLE_PURCHASE_PRICES_FAIL";
