export const MATERIAL_CONSUMPTION_LIST_REQUEST =
  "MATERIAL_CONSUMPTION_LIST_REQUEST";
export const MATERIAL_CONSUMPTION_LIST_SUCCESS =
  "MATERIAL_CONSUMPTION_LIST_SUCCESS";
export const MATERIAL_CONSUMPTION_LIST_FAIL = "MATERIAL_CONSUMPTION_LIST_FAIL";
export const MATERIAL_CONSUMPTION_LIST_RESET =
  "MATERIAL_CONSUMPTION_LIST_RESET";
