export const MATERIAL_IMPORT_LIST_REQUEST = "MATERIAL_IMPORT_LIST_REQUEST";
export const MATERIAL_IMPORT_LIST_SUCCESS = "MATERIAL_IMPORT_LIST_SUCCESS";
export const MATERIAL_IMPORT_LIST_FAIL = "MATERIAL_IMPORT_LIST_FAIL";
export const MATERIAL_IMPORT_LIST_RESET = "MATERIAL_IMPORT_LIST_RESET";
