export const MATERIAL_LAGER_LIST_REQUEST = "MATERIAL_LAGER_LIST_REQUEST";
export const MATERIAL_LAGER_LIST_SUCCESS = "MATERIAL_LAGER_LIST_SUCCESS";
export const MATERIAL_LAGER_LIST_FAIL = "MATERIAL_LAGER_LIST_FAIL";
export const MATERIAL_LAGER_LIST_RESET = "MATERIAL_LAGER_LIST_RESET";

export const LAGER_MATERIAL_LIST_REQUEST = "LAGER_MATERIAL_LIST_REQUEST";
export const LAGER_MATERIAL_LIST_SUCCESS = "LAGER_MATERIAL_LIST_SUCCESS";
export const LAGER_MATERIAL_LIST_FAIL = "LAGER_MATERIAL_LIST_FAIL";

export const MATERIAL_LAGER_QUANTITIES_REQUEST =
  "MATERIAL_LAGER_QUANTITIES_REQUEST";
export const MATERIAL_LAGER_QUANTITIES_SUCCESS =
  "MATERIAL_LAGER_QUANTITIES_SUCCESS";
export const MATERIAL_LAGER_QUANTITIES_FAIL = "MATERIAL_LAGER_QUANTITIES_FAIL";
