export const PARTNER_LIST_REQUEST = "PARTNER_LIST_REQUEST";
export const PARTNER_LIST_SUCCESS = "PARTNER_LIST_SUCCESS";
export const PARTNER_LIST_FAIL = "PARTNER_LIST_FAIL";

export const PARTNER_CREATE_REQUEST = "PARTNER_CREATE_REQUEST";
export const PARTNER_CREATE_SUCCESS = "PARTNER_CREATE_SUCCESS";
export const PARTNER_CREATE_FAIL = "PARTNER_CREATE_FAIL";
export const PARTNER_CREATE_RESET = "PARTNER_CREATE_RESET";
