export const PRODUCT_LAGER_LIST_REQUEST = "PRODUCT_LAGER_LIST_REQUEST";
export const PRODUCT_LAGER_LIST_SUCCESS = "PRODUCT_LAGER_LIST_SUCCESS";
export const PRODUCT_LAGER_LIST_FAIL = "PRODUCT_LAGER_LIST_FAIL";
export const PRODUCT_LAGER_LIST_RESET = "PRODUCT_LAGER_LIST_RESET";

export const PRODUCT_EXPORT_CREATE_REQUEST = "PRODUCT_EXPORT_CREATE_REQUEST";
export const PRODUCT_EXPORT_CREATE_SUCCESS = "PRODUCT_EXPORT_CREATE_SUCCESS";
export const PRODUCT_EXPORT_CREATE_FAIL = "PRODUCT_EXPORT_CREATE_FAIL";
export const PRODUCT_EXPORT_CREATE_RESET = "PRODUCT_EXPORT_CREATE_RESET";
