export const RATE_LIST_REQUEST = "RATE_LIST_REQUEST";
export const RATE_LIST_SUCCESS = "RATE_LIST_SUCCESS";
export const RATE_LIST_FAIL = "RATE_LIST_FAIL";

export const RATE_CREATE_REQUEST = "RATE_CREATE_REQUEST";
export const RATE_CREATE_SUCCESS = "RATE_CREATE_SUCCESS";
export const RATE_CREATE_FAIL = "RATE_CREATE_FAIL";
export const RATE_CREATE_RESET = "RATE_CREATE_RESET";
