export const RATE_LIST_REQUEST = "RATE_LIST_REQUEST";
export const RATE_LIST_SUCCESS = "RATE_LIST_SUCCESS";
export const RATE_LIST_FAIL = "RATE_LIST_FAIL";
export const RATE_LIST_RESET = "RATE_LIST_RESET";

export const RATE_DETAILS_REQUEST = "RATE_DETAILS_REQUEST";
export const RATE_DETAILS_SUCCESS = "RATE_DETAILS_SUCCESS";
export const RATE_DETAILS_FAIL = "RATE_DETAILS_FAIL";
export const RATE_DETAILS_RESET = "RATE_DETAILS_RESET";

export const RATE_CREATE_REQUEST = "RATE_CREATE_REQUEST";
export const RATE_CREATE_SUCCESS = "RATE_CREATE_SUCCESS";
export const RATE_CREATE_FAIL = "RATE_CREATE_FAIL";
export const RATE_CREATE_RESET = "RATE_CREATE_RESET";
