export const REQUISITION_LIST_REQUEST = "REQUISITION_LIST_REQUEST";
export const REQUISITION_LIST_SUCCESS = "REQUISITION_LIST_SUCCESS";
export const REQUISITION_LIST_FAIL = "REQUISITION_LIST_FAIL";
export const REQUISITION_LIST_RESET = "REQUISITION_LIST_RESET";

export const REQUISITION_UNFULLFILLED_LIST_REQUEST =
  "REQUISITION_UNFULLFILLED_LIST_REQUEST";
export const REQUISITION_UNFULLFILLED_LIST_SUCCESS =
  "REQUISITION_UNFULLFILLED_LIST_SUCCESS";
export const REQUISITION_UNFULLFILLED_LIST_FAIL =
  "REQUISITION_UNFULLFILLED_LIST_FAIL";
export const REQUISITION_UNFULLFILLED_LIST_RESET =
  "REQUISITION_UNFULLFILLED_LIST_RESET";

export const REQUISITION_CREATE_REQUEST = "REQUISITION_CREATE_REQUEST";
export const REQUISITION_CREATE_SUCCESS = "REQUISITION_CREATE_SUCCESS";
export const REQUISITION_CREATE_FAIL = "REQUISITION_CREATE_FAIL";
export const REQUISITION_CREATE_RESET = "REQUISITION_CREATE_RESET";

export const REQUISITION_FULLFILL_REQUEST = "REQUISITION_FULLFILL_REQUEST";
export const REQUISITION_FULLFILL_SUCCESS = "REQUISITION_FULLFILL_SUCCESS";
export const REQUISITION_FULLFILL_FAIL = "REQUISITION_FULLFILL_FAIL";
