export const SALE_RECEIPT_LIST_REQUEST = "SALE_RECEIPT_LIST_REQUEST";
export const SALE_RECEIPT_LIST_SUCCESS = "SALE_RECEIPT_LIST_SUCCESS";
export const SALE_RECEIPT_LIST_FAIL = "SALE_RECEIPT_LIST_FAIL";
export const SALE_RECEIPT_LIST_RESET = "SALE_RECEIPT_LIST_RESET";

export const SALE_RECEIPT_CREATE_REQUEST = "SALE_RECEIPT_CREATE_REQUEST";
export const SALE_RECEIPT_CREATE_SUCCESS = "SALE_RECEIPT_CREATE_SUCCESS";
export const SALE_RECEIPT_CREATE_FAIL = "SALE_RECEIPT_CREATE_FAIL";
export const SALE_RECEIPT_CREATE_RESET = "SALE_RECEIPT_CREATE_RESET";
