export const WORKORDER_LIST_REQUEST = "WORKORDER_LIST_REQUEST";
export const WORKORDER_LIST_SUCCESS = "WORKORDER_LIST_SUCCESS";
export const WORKORDER_LIST_FAIL = "WORKORDER_LIST_FAIL";
export const WORKORDER_LIST_RESET = "WORKORDER_LIST_RESET";

export const WORKORDER_CREATE_REQUEST = "WORKORDER_CREATE_REQUEST";
export const WORKORDER_CREATE_SUCCESS = "WORKORDER_CREATE_SUCCESS";
export const WORKORDER_CREATE_FAIL = "WORKORDER_CREATE_FAIL";
export const WORKORDER_CREATE_RESET = "WORKORDER_CREATE_RESET";
