export const WORKORDER_LIST_REQUEST = "WORKORDER_LIST_REQUEST";
export const WORKORDER_LIST_SUCCESS = "WORKORDER_LIST_SUCCESS";
export const WORKORDER_LIST_FAIL = "WORKORDER_LIST_FAIL";
export const WORKORDER_LIST_RESET = "WORKORDER_LIST_RESET";

export const WORKORDER_DETAILS_REQUEST = "WORKORDER_DETAILS_REQUEST";
export const WORKORDER_DETAILS_SUCCESS = "WORKORDER_DETAILS_SUCCESS";
export const WORKORDER_DETAILS_FAIL = "WORKORDER_DETAILS_FAIL";
export const WORKORDER_DETAILS_RESET = "WORKORDER_DETAILS_RESET";

export const WORKORDER_PROGRESS_REQUEST = "WORKORDER_PROGRESS_REQUEST";
export const WORKORDER_PROGRESS_SUCCESS = "WORKORDER_PROGRESS_SUCCESS";
export const WORKORDER_PROGRESS_FAIL = "WORKORDER_PROGRESS_FAIL";
export const WORKORDER_PROGRESS_RESET = "WORKORDER_PROGRESS_RESET";

export const WORKORDER_FINISHED_REQUEST = "WORKORDER_FINISHED_REQUEST";
export const WORKORDER_FINISHED_SUCCESS = "WORKORDER_FINISHED_SUCCESS";
export const WORKORDER_FINISHED_FAIL = "WORKORDER_FINISHED_FAIL";
export const WORKORDER_FINISHED_RESET = "WORKORDER_FINISHED_RESET";

export const WORKORDER_CREATE_REQUEST = "WORKORDER_CREATE_REQUEST";
export const WORKORDER_CREATE_SUCCESS = "WORKORDER_CREATE_SUCCESS";
export const WORKORDER_CREATE_FAIL = "WORKORDER_CREATE_FAIL";
export const WORKORDER_CREATE_RESET = "WORKORDER_CREATE_RESET";

export const WORKORDER_UPDATE_REQUEST = "WORKORDER_UPDATE_REQUEST";
export const WORKORDER_UPDATE_SUCCESS = "WORKORDER_UPDATE_SUCCESS";
export const WORKORDER_UPDATE_FAIL = "WORKORDER_UPDATE_FAIL";
export const WORKORDER_UPDATE_RESET = "WORKORDER_UPDATE_RESET";
